In [9]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


I = np.array([0.9, 0.1, 0.8]).reshape(3, 1)
W = np.array([
    [0.9, 0.3, 0.4],
    [0.2, 0.8, 0.2],
    [0.1, 0.5, 0.6]
])

X = np.dot(W, I)

Y = sigmoid(X)

print(I, I.shape)
print(W, W.shape)
print(X, X.shape)
print(Y, Y.shape)

[[0.9]
 [0.1]
 [0.8]] (3, 1)
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]] (3, 3)
[[1.16]
 [0.42]
 [0.62]] (3, 1)
[[0.76133271]
 [0.60348325]
 [0.65021855]] (3, 1)


In [27]:
import numpy as np

x = np.arange(1, 5).reshape(2, 2)
y = np.arange(5, 11).reshape(2, 3)

print(x)
print(y)

print(np.dot(x, y))
print(y[:, 1:])
print(x * y[:, 1:])

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]
[[21 24 27]
 [47 54 61]]
[[ 6  7]
 [ 9 10]]
[[ 6 14]
 [27 40]]


### numpy.reshape()

不改变原形状。

In [43]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a: {a.shape} = \n{a}')

b = np.reshape(a, (3, 2))
print(f'b: {b.shape} = \n{b}')

print(f'a: {a.shape} = \n{a}')

print(a.reshape(3, 2))
print(a.reshape(-1, 2))
print(a.reshape(3, -1))

a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
b: (3, 2) = 
[[1 2]
 [3 4]
 [5 6]]
a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


### arr.reshape()
不改变原形状。

In [45]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a: {a.shape} = \n{a}')

b = a.reshape((3, 2))
print(f'b: {b.shape} = \n{b}')

print(f'a: {a.shape} = \n{a}')

print(a.reshape(3, 2))
print(a.reshape(-1, 2))
print(a.reshape(3, -1))

a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
b: (3, 2) = 
[[1 2]
 [3 4]
 [5 6]]
a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


### numpy.resize()
不改变原形状。

In [48]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a: {a.shape} = \n{a}')

b = np.resize(a, (3, 2))
print(f'b: {b.shape} = \n{b}')

print(f'a: {a.shape} = \n{a}')

a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
b: (3, 2) = 
[[1 2]
 [3 4]
 [5 6]]
a: (2, 3) = 
[[1 2 3]
 [4 5 6]]


### arr.resize()

改变原形状。

无返回值。


In [39]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f'a: {a.shape} = \n{a}')

a.resize((3, 2))

print(f'a: {a.shape} = \n{a}')

a: (2, 3) = 
[[1 2 3]
 [4 5 6]]
a: (3, 2) = 
[[1 2]
 [3 4]
 [5 6]]


## 性能问题

### x = x + y vs x += y

In [7]:
import numpy as np

x = np.arange(1, 10, 2)
print(x, type(x), id(x))

y = np.zeros_like(x)
print(y, type(y), id(y))

x = x + y
print(x, type(x), id(x))


[1 3 5 7 9] <class 'numpy.ndarray'> 4455255088
[0 0 0 0 0] <class 'numpy.ndarray'> 4479486832
[1 3 5 7 9] <class 'numpy.ndarray'> 4479187920


In [9]:
import numpy as np

x = np.arange(1, 10, 2)
print(x, type(x), id(x))

y = np.zeros_like(x)
print(y, type(y), id(y))

x += y
print(x, type(x), id(x))

[1 3 5 7 9] <class 'numpy.ndarray'> 4466367088
[0 0 0 0 0] <class 'numpy.ndarray'> 4479185424
[1 3 5 7 9] <class 'numpy.ndarray'> 4466367088


In [1]:
x = [i for i in range(1, 10, 2)]
print(x, type(x), id(x))

y = [i for i in range(1, 10, 2)]
print(y, type(x), id(y))

x = x + y
print(x, type(x), id(x))

[1, 3, 5, 7, 9] <class 'list'> 4578943104
[1, 3, 5, 7, 9] <class 'list'> 4578941184
[1, 3, 5, 7, 9, 1, 3, 5, 7, 9] <class 'list'> 4578939328


In [13]:
x = [i for i in range(1, 10, 2)]
print(id(x), type(x))

y = [i for i in range(1, 1000000)]
# print(id(y), type(x), y)

x += y
print(id(x), type(x))

4578993344 <class 'list'>
4578993344 <class 'list'>


In [16]:
x = [i for i in range(1, 10)]
y = [1, 2, 3]
print(x, y)
z = x - y
print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9] [1, 2, 3]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

## 广播机制

In [22]:
import numpy as np

print('-' * 10)
a = np.arange(1, 13).reshape(2, 3, 2)
print(a.shape)
print(a)

print('-' * 10)
b = np.arange(1, 7).reshape(3, 2)
print(b.shape)
print(b)

print('-' * 10)
c = a + b
print(c.shape)
print(c)


----------
(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
----------
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
----------
(2, 3, 2)
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[ 8 10]
  [12 14]
  [16 18]]]
