## Numpy ufunc 对象

In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

print(np.sin(a))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
