In [1]:
len?

In [58]:
len??

In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [60]:
lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %code_wrap  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %mamba  %man  %matplotlib  %micromamba  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %

In [61]:
%run?

In [62]:
%run 00-jupyter-hello.py

Hello python world~!


In [63]:
%time hello()

Hello python world~!
CPU times: user 254 µs, sys: 110 µs, total: 364 µs
Wall time: 310 µs


In [64]:
%timeit -r 1 -n 3 hello()

Hello python world~!
Hello python world~!
Hello python world~!
138 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)


In [65]:
%%timeit -r 1 -n 3
hello()

Hello python world~!
Hello python world~!
Hello python world~!
134 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 3 loops each)


In [66]:
def bubble(my_list):
    for i in range(len(my_list) - 1):
        for j in range(len(my_list) - i - 1):
            if my_list[j] > my_list[j + 1]:
                my_list[j], my_list[j + 1] = my_list[j + 1], my_list[j]
    return my_list

In [67]:
bubble([1, 2, 4, 3, 7, 9, 8])

[1, 2, 3, 4, 7, 8, 9]

In [2]:
import numpy as np

nd = np.arange(25).reshape(5, 5)

print(nd)

print(nd[2::2, ::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 12 14]
 [20 22 24]]


In [1]:
import numpy as np

nd = np.arange(5).T
print(nd)
print(nd[2::2])

[0 1 2 3 4]
[2 4]
